string(ASCII 27 esc)

set(nc "${esc}[0m")
set(bold "${esc}[1m")

set(fg_black   "${esc}[30m")
set(fg_red     "${esc}[31m")
set(fg_green   "${esc}[32m")
set(fg_yellow  "${esc}[33m")
set(fg_blue    "${esc}[34m")
set(fg_magenta "${esc}[35m")
set(fg_cyan    "${esc}[36m")
set(fg_white   "${esc}[37m")

set(fg_h_black   "${esc}[90m")
set(fg_h_red     "${esc}[91m")
set(fg_h_green   "${esc}[92m")
set(fg_h_yellow  "${esc}[93m")
set(fg_h_blue    "${esc}[94m")
set(fg_h_magenta "${esc}[95m")
set(fg_h_cyan    "${esc}[96m")
set(fg_h_white   "${esc}[97m")

set(bg_black   "${esc}[40m")
set(bg_red     "${esc}[41m")
set(bg_green   "${esc}[42m")
set(bg_yellow  "${esc}[43m")
set(bg_blue    "${esc}[44m")
set(bg_magenta "${esc}[45m")
set(bg_cyan    "${esc}[46m")
set(bg_white   "${esc}[47m")

set(bg_h_black   "${esc}[100m")
set(bg_h_red     "${esc}[101m")
set(bg_h_green   "${esc}[102m")
set(bg_h_yellow  "${esc}[103m")
set(bg_h_blue    "${esc}[104m")
set(bg_h_magenta "${esc}[105m")
set(bg_h_cyan    "${esc}[106m")
set(bg_h_white   "${esc}[107m")
